### ISSUE TITLE
[ROS2] Bondcpp statemap::TransitionUndefinedException 

### ISSUE THREAD

**Issue by xander-m2k** [ros/bond_core#82]
Currently trying to get bondcpp working:

This is my main:
```
int main(int argc, char **argv)
{
	rclcpp::init(argc, argv);
	rclcpp::executors::SingleThreadedExecutor exec;

	auto robot_bond = std::make_shared<RobotBond>();
	auto pickplace = std::make_shared<PickPlaceDemo>(robot_bond);

	exec.add_node(robot_bond->get_node_base_interface());
	exec.add_node(pickplace);

        exec.spin();
	rclcpp::shutdown();

	return 0;
}
```
In the constructor of PickPlace demo I call `robot_bond->startBond()`.

This is my Bond class
```
RobotBond::RobotBond() 
    : rclcpp_lifecycle::LifecycleNode("bond_node_client")
{
}

void RobotBond::startBond(){
    if (client_bond_ && !client_bond_->isBroken()) // skip starting if already bonded
        return;

    RCLCPP_INFO_STREAM(rclcpp::get_logger("tm_ros"),"[TM Bonding]: starting bonding node.");

    client_bond_ = std::unique_ptr<bond::Bond>(new bond::Bond("/tm_driver_bond", this->get_name(),
        this->shared_from_this(),
        std::bind(&RobotBond::onClientBoundBrokenCallback, this), 
        std::bind(&RobotBond::onClientBoundFormedCallback, this)
        )); 

    client_bond_->setHeartbeatPeriod(0.5);
    client_bond_->setHeartbeatTimeout(1);

    client_bond_->start();
    RCLCPP_INFO_STREAM(rclcpp::get_logger("tm_ros"),"[TM Bonding]: bonding node has started");
}

void RobotBond::onClientBoundFormedCallback(){
    RCLCPP_INFO_STREAM(rclcpp::get_logger("tm_ros"),"[TM Bonding]: bond to client established.");
}

void RobotBond::onClientBoundBrokenCallback(){
}
```

The exception I am getting:
```
terminate called after throwing an instance of 'statemap::TransitionUndefinedException'
  what():  no such transition in current state
```

The error is thrown by the `smclib`, I'm not really understanding why. I guess the `BondSM` is not correctly set when instantiating the class. Please advice on solving this problem.

**Comment by mjcarroll** [comment]
@xander-m2k are you still experiencing this issue?  Can you maybe capture a larger backtrace?

**Comment by xander-m2k** [comment]
> @xander-m2k are you still experiencing this issue?  Can you maybe capture a larger backtrace?

I have skipped this library and implemented my own custom heartbeat, because of this issue. It has been too long since this issue to reproduce this correctly, I am sorry.

**Comment by dtabacaru** [comment]
I am also trying to get bond working in ROS2 and am running into this same problem.

I have reproduced it by slightly modifying the test found in test_bond/test/test_callbacks_cpp.cpp

```  
  rclcpp::init(0, nullptr);
  auto nh1 = rclcpp::Node::make_shared("test_callbacks_cpp");
  std::string id1 = "bleh";
  bond::Bond a("/top/topic", id1, nh1);
  bond::Bond b("/top/topic", id1, nh1);

  a.setFormedCallback(
      [&a]() {
        a.breakBond();
      });
  a.start();
  //b.start();

  std::atomic<bool> isRunning {true};
  auto runThread = std::thread(
      [&isRunning, &nh1]() {
        while (isRunning) {
          rclcpp::spin_some(nh1);
        }
      });

  EXPECT_TRUE(a.waitUntilFormed(rclcpp::Duration(5.0s)));
  //EXPECT_TRUE(b.waitUntilBroken(rclcpp::Duration(3.0s)));

  isRunning = false;
  runThread.join();
```

Running this, we get the error:

```
/home/dtabacaru/Development/colcon_ws/src/watchdog/cmake-build-debug/bin/watchdog_node
terminate called after throwing an instance of 'statemap::TransitionUndefinedException'
  what():  no such transition in current state

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

Note that it happens faster than the default connect timeout of 10 seconds. It takes roughly 5 seconds to have this problem show up.

My application requires a possibly indeterminate connection timeout which in ROS1 I was getting away with by setting a very large number.

Now it seems the connect timeout does not matter since this error occurs first.

**Comment by riv-tnoble** [comment]
I'm also running into this issue in ROS2. Can it be re-opened as it's clearly still a problem?

**Comment by riv-tnoble** [comment]
Backtrace:

```
0x00007d15e273a9fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007d15e273a9fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007d15e26e6476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007d15e26cc7f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007d15e298fb9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007d15e299b20c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007d15e299b277 in std::terminate() ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007d15e299b4d8 in __cxa_throw ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007d15e2640279 in BondSMState::Default(BondSMContext&) ()
   from /opt/ros/humble/lib/libbondcpp.so
#8  0x00007d15e264ca2f in bond::Bond::onHeartbeatTimeout() ()
   from /opt/ros/humble/lib/libbondcpp.so
#9  0x00007d15e2664a15 in ?? () from /opt/ros/humble/lib/libbondcpp.so
#10 0x00007d15e2c87031 in rclcpp::Executor::execute_any_executable(rclcpp::AnyExecutable&) () from /opt/ros/humble/lib/librclcpp.so
#11 0x00007d15e2c8e34a in rclcpp::executors::MultiThreadedExecutor::run(unsigned long) () from /opt/ros/humble/lib/librclcpp.so
#12 0x00007d15e29c9253 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007d15e2738ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x00007d15e27c9a04 in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
